### ISSUE TITLE
Optional installation?

### ISSUE THREAD

**Issue by afragen** [afragen/wp-dependency-installer#1] opened 2016-01-23 23:15 UTC
From @mgibbs189

Some users might not want plugins to be installed automatically. In each item's JSON settings, what are your thoughts on supporting an (optional) confirm setting? If it exists and is set to TRUE, the user will need to confirm installation (by clicking an "Install" link within an admin notice).

``` json
{
  "github-updater": {
    "name": "GitHub Updater",
    "slug": "github-updater/github-updater.php",
    "git": "github",
    "uri": "https://github.com/afragen/github-updater",
    "branch": "master",
    "confirm": true,
    "token":null
  }
}
```

**Comment by afragen** [comment] 2016-01-23 23:50
https://github.com/afragen/wp-install-dependencies/commit/1b4c5d88d213dce095d095db387dc5c21aca8895 should take care of this.

Contents of `wp-dependencies.json` now passed into class instantiation.

**Comment by afragen** [comment] 2016-01-23 23:53
This may be a bit more difficult than we think. Besides, if a plugin is truly a dependency, shouldn't it always be installed and activated?

**Comment by mgibbs189** [comment] 2016-01-24 00:16
Not necessarily. A plugin could be an optional dependency. E.g. it's not required for the original plugin to run, but would enable extra functionality of the original plugin when active.

Regarding the code above, I probably should've changed the param from `confirm` to `optional`.

**Comment by afragen** [comment] 2016-01-24 01:51
If the dependency is optional should we ask to install, install and not activate, or something different? Right now I'm not sure. I haven't really thought about how to make it optional.

**Comment by mgibbs189** [comment] 2016-01-24 02:00
Here's an idea for optional dependencies:

<img src="http://i.imgur.com/IgU7cmP.png" width="620" height="152" />

When a user clicks `Install Now`, the plugin will be installed and activated.

**Comment by afragen** [comment] 2016-01-24 07:39
I can certainly code that up, but we would have to figure something about the text as it would need to be more generic.

So optional dependencies would be listed under the plugin wanting them installed.

**Comment by afragen** [comment] 2016-01-24 16:23
I think is going to require the json file, and likely a bit of code, to be rewritten. No other clean way to ensure that the dependencies are correctly listed with their plugins.

**Comment by afragen** [comment] 2016-01-24 21:02
Matt, I have to say I'm failing in trying to get that **Install Now** link to work.

Somehow I need to use the link to run the `install()` method but it's not working for me.

**Comment by mgibbs189** [comment] 2016-01-24 23:09
I'll try to take a look early next week. We may want to step back from the code and try to nail down all the requirements first.

**Comment by afragen** [comment] 2016-01-25 00:29
I just merged much of what I was working on today. It will install all listed plugins but will not activate optional dependencies. Additionally, the dependent plugin and all dependencies are labeled. FYI, if testing the json format changed.

**Comment by afragen** [comment] 2016-01-27 06:24
So I tried merging what you've done with this to allow for a json config file and multiple plugins. It's in the `js-install` branch. I can't seem to get the javascript to work in the `after_plugin_row_`. Heck, I'm totally lost with this at the moment. :stuck_out_tongue_closed_eyes:

**Comment by mgibbs189** [comment] 2016-01-27 12:29
Haha, I'll check it out shortly.

**Comment by afragen** [comment] 2016-01-27 14:28
Thanks Matt

**Comment by afragen** [comment] 2016-01-28 21:42
I've got the additional plugin rows for each optional install listed but the don't work. :stuck_out_tongue_closed_eyes: 

It would be great and future proof concept to be able to have them install similarly to how shiny updates work.

**Comment by mgibbs189** [comment] 2016-01-28 21:52
How were you thinking it would look when a plugin has multiple dependencies?
- Should each dependency be on its own line, with an "Install" button beside it?
- Should a single "This plugin has dependencies" link appear, and clicking it would show a Modal box with all dependencies?
- Should there be an "Install All Dependencies" link appear somewhere?

You're right... optional dependencies make things a lot more complicated :wink:

**Comment by afragen** [comment] 2016-01-28 22:36
It would likely look and feel most like core if each dependency were on it's own line with an 'Install' button. If the install then looks/works like shiny updates then it's a bonus. 

Once installed the line would then disappear, on a page reload. If the dependency is installed and not activated, we should probably include an 'Activate' button.

**Comment by afragen** [comment] 2016-02-04 16:58
@mgibbs189 I just had a thought as another dev was interested in this for his themes, the current method of adding to `after_plugin_row_` won't work consistently for themes. Rather than reinvent a new method for themes I think returning to a functionality within an admin notices is the way to go.

I'm going to make a new branch for this and we should probably work along that path. Let me know your thoughts.

**Comment by mgibbs189** [comment] 2016-02-04 17:58
@afragen Are we just referring to plugins able to register themes as dependencies? Or can a theme itself require another theme as a dependency?

Sorry for the delay, been swamped with FacetWP work this week

**Comment by afragen** [comment] 2016-02-04 18:48
No, a theme registering plugins as dependencies. As we consciously try to get theme developers to separate form and function, they will require certain plugins for function.

Don't worry about being swamped with paid work. :+1:

**Comment by afragen** [comment] 2016-02-06 02:02
@mgibbs189 I made a number of simplifications to `js-install-admin-notice` and fixed it to work with themes.

Of course, we ( you :smiling_imp: ) still need to get the js working.

**Closed as completed** 2016-02-13 01:16 UTC
Labels: enhancement

**Comment by senlin** [comment] 2017-05-12 17:28
I understand that this (optional dependency) never saw the light of day?

**Comment by afragen** [comment] 2017-05-12 17:33
@senlin it's there. It will show up in an admin notice. The admin notice is dismissable for a week at a time.

What didn't work was adding the dependencies to the after_plugin_row or after_theme_row.

Just add `"optional: true"` to the JSON.

**Comment by senlin** [comment] 2017-05-12 17:43
The thing is that the notice actually cannot be dismissed; after a refresh it pops right up again.

we posted at the same time, so in the json file I'm doing it correct.

Yeah, the after_plugin_row would have been very nice :)

**Comment by senlin** [comment] 2017-05-12 17:50
You can try this out using my [lean-wp plugin](https://gitbub.com/senlin/lean-wp). I have just added there admin menu manager plugin as "optional". If you don't activate that plugin and dismiss the notice, it comes right back at you after a refresh.

Also a nice addition would be to only show the notice on the Plugins page, not on the other backend pages as that might come across as pretty irritating ;)

**Comment by afragen** [comment] 2017-05-12 18:01
I just tried it out using lean-wp. The required plugins installed and activated. The optional plugin admin notice did not reappear on any page reload after being dismissed.

Do you have something interfering with transients perhaps?

**Comment by senlin** [comment] 2017-05-12 18:04
huh? 
That is strange, the only 2 other plugins that are active on my dev site are Yoast SEO and Hide SEO Bloat and then there is a deactivated Jetpack.

I will reset the lot and report back.

**Comment by afragen** [comment] 2017-05-12 18:07
I hope the Lean-WP plugin is also active. 😉

**Comment by senlin** [comment] 2017-05-12 18:12
hahaha, yup it is.

Did a reset with a default theme (twentyseventeen) and still the dismissed notice returns right after the page refresh.

**Comment by afragen** [comment] 2017-05-12 18:14
Strange. Any caching?

**Comment by senlin** [comment] 2017-05-12 18:18
nope, trying another live site now...

**Comment by senlin** [comment] 2017-05-12 18:21
same thing, cannot dismiss it.

**Comment by afragen** [comment] 2017-05-12 18:22
Did it disappear when you dismissed it by clicking the dismiss icon?

**Comment by senlin** [comment] 2017-05-12 18:25
Yes, it disappears when I click the dismiss icon. And then I visit the Dashboard or any other page in the backend and then it shows again.

**Comment by afragen** [comment] 2017-05-12 18:27
Can you test locally? It did work for me on my test site.

**Comment by senlin** [comment] 2017-05-12 18:31
Also locally doesn't work. Dismissing works, but after refresh the whole text is back again. 

Hopefully we are talking about the same thing?

![plugins_ _bizpress_ _wordpress](https://cloud.githubusercontent.com/assets/650066/26011589/3e7109f4-3741-11e7-8700-822e1eb3b0db.png)

**Comment by afragen** [comment] 2017-05-12 18:32
We are talking about the same thing.

**Comment by afragen** [comment] 2017-05-12 18:34
I only tested dismissing the install not the activation. Let me test.

**Comment by senlin** [comment] 2017-05-12 18:37
dismissing the install gives the same result for me: also comes back :(

**Comment by afragen** [comment] 2017-05-12 18:39
Unfortunately I'm away for the weekend and don't have my laptop. It's still dismissed for me after reinstalling and re-activating. I'll have to figure out how to remove the transient before I can test more.

**Comment by senlin** [comment] 2017-05-12 18:47
No worries Andy, please enjoy your weekend!

This is not something urgent and I am not even entirely sure whether I need to include that plugin as there seem to be a few hiccups, which basically is also the reason I want to make it an optional dependency in the first place...

I won't be releasing Lean WP this weekend, so that's all right and I can always add the dependency later on!

Have a great weekend!

**Comment by afragen** [comment] 2017-05-12 18:53
Out of curiousity are there any JS errors after you click the dismiss?

**Comment by senlin** [comment] 2017-05-12 18:56
As far as I can see, not

**Comment by senlin** [comment] 2017-05-12 18:59
and right after clicking the dismiss icon I can see this in the console

![plugins_ _wp_dev_ _wordpress](https://cloud.githubusercontent.com/assets/650066/26012748/2030386c-3745-11e7-8c66-778e8cbd4ce9.png)

**Comment by senlin** [comment] 2017-05-12 19:00
The Post tab of that console shows this
![plugins_ _wp_dev_ _wordpress](https://cloud.githubusercontent.com/assets/650066/26012806/4d43f834-3745-11e7-85d8-f8d783c41db1.png)

**Comment by senlin** [comment] 2017-05-12 19:02
Response is empty

**Comment by afragen** [comment] 2017-05-12 19:05
I'll have to test more next week.

**Comment by senlin** [comment] 2017-05-12 19:07
Sure, no worries, I need to run now too.

Talk later.

**Comment by afragen** [comment] 2017-05-12 19:11
There should be a `slug` param present.

**Comment by senlin** [comment] 2017-05-12 19:11
not there I'm afraid :(

**Comment by afragen** [comment] 2017-05-12 19:12
https://github.com/afragen/wp-dependency-installer/blob/develop/wp-dependency-installer.php#L227

**Comment by afragen** [comment] 2017-05-20 05:18
@senlin I've been playing around and if you've got an object cache running then the transient storing the timeout gets stored there. If that cache clears sooner, and it's likely to, then the notice will come back sooner.

**Comment by senlin** [comment] 2017-05-20 20:43
The problem that I have been experiencing is that the notice comes back on page refresh. And the backend usually doesn't use caching or does it?

**Comment by senlin** [comment] 2017-08-18 20:01
Hi Andy, how are you doing?
As you can see from the referenced thread, this issue has popped up its head again.

Is there anything that can be done to resolve this?

**Comment by afragen** [comment] 2017-08-18 21:35
The admin notice should be dismissed for a week.

**Comment by senlin** [comment] 2017-08-18 22:00
Yes, it should, but it seems that sometimes it works and sometimes it doesn't. 

I have tried to find the period of one week in the code and cannot find it. If I can, then I can simply change it to forever. Is there a way to do that?

**Comment by afragen** [comment] 2017-08-18 22:05
The line is here, https://github.com/afragen/wp-dependency-installer/blob/master/wp-dependency-installer.php#L380

The `-7` should be changed to `-forever`, I think. That's in the other library and I'll have to check. 

I'll try to test again in a clean install this weekend.

**Comment by senlin** [comment] 2017-08-18 22:16
Thanks Andy, before I change the number I will await your tests then.

**Comment by afragen** [comment] 2017-08-19 03:55
@senlin I think the issue is I needed to ensure that the admin notice dismissal dependency is initialized. I have it initialized in another plugin so I missed it here.

Replace your current `wp-dependency-installer.php` with the one from `develop`.

Let me know if the dismissal works. If it works, I'll push to master and a release so a `composer update` will bring in the changes.

**Comment by senlin** [comment] 2017-08-19 08:02
Hi @afragen it looks like you nailed it! 

I can confirm that using the `wp-dependency-installer.php` of the `develop` branch indeed enables dismissing the notice and keeping it dismissed after a refresh.

Regarding the `composer update` should I run that in my own repo? I can't just replace the file? 

P.S. I already checked the time of dismissal in [the other library](https://github.com/senlin/lean-wp/blob/v1.1.0/vendor/collizo4sky/persist-admin-notices-dismissal/persist-admin-notices-dismissal.php#L80) and it seems to be `'forever'`, not `'-forever'`.

**Comment by afragen** [comment] 2017-08-19 14:32
You can just replace the file.

**Comment by senlin** [comment] 2017-08-19 16:21
figured it out with `composer update` :)
many thanks that this issue is finally solved and wish you a great weekend!
